var nhoodscolors = [{"NEIGHBORHOOD":"Lakeview","COLOR":"dot-blue-mud"},
{"NEIGHBORHOOD":"Lake View","COLOR":"dot-blue-mud"},
{"NEIGHBORHOOD":"Sorta Lakeview","COLOR":"dot-blue-mud"},
{"NEIGHBORHOOD":"Treeview (can't see no lake)","COLOR":"dot-blue-mud"},
{"NEIGHBORHOOD":"Poor Lakeview","COLOR":"dot-blue-mud"},
{"NEIGHBORHOOD":"Poor","COLOR":"dot-blue-mud"},
{"NEIGHBORHOOD":"Edge of Lakeview","COLOR":"dot-blue-mud"},
{"NEIGHBORHOOD":"Lakeview's Hat","COLOR":"dot-blue-mud"},
{"NEIGHBORHOOD":"LV","COLOR":"dot-blue-mud"},
{"NEIGHBORHOOD":"The view","COLOR":"dot-blue-mud"},
{"NEIGHBORHOOD":"Wannabe Lakeview","COLOR":"dot-blue-mud"},
{"NEIGHBORHOOD":"West End-Lakeview","COLOR":"dot-gray-warm-dk"},
{"NEIGHBORHOOD":"West End / Lakeview","COLOR":"dot-gray-warm-dk"},
{"NEIGHBORHOOD":"West End/Lakeview","COLOR":"dot-gray-warm-dk"},
{"NEIGHBORHOOD":"West End","COLOR":"dot-gray-warm-dk"},
{"NEIGHBORHOOD":"Westend","COLOR":"dot-gray-warm-dk"},
{"NEIGHBORHOOD":"City Park / Bayou St John","COLOR":"dot-blue-navy"},
{"NEIGHBORHOOD":"citypark","COLOR":"dot-blue-navy"},
{"NEIGHBORHOOD":"By the Park","COLOR":"dot-blue-navy"},
{"NEIGHBORHOOD":"City Park East","COLOR":"dot-blue-navy"},
{"NEIGHBORHOOD":"City Park","COLOR":"dot-blue-navy"},
{"NEIGHBORHOOD":"City Park Area","COLOR":"dot-blue-navy"},
{"NEIGHBORHOOD":"Navarre","COLOR":"dot-pink"},
{"NEIGHBORHOOD":"Navare","COLOR":"dot-pink"},
{"NEIGHBORHOOD":"Park Place","COLOR":"dot-green-fq"},
{"NEIGHBORHOOD":"City Park Place","COLOR":"dot-green-fq"},
{"NEIGHBORHOOD":"Park Places","COLOR":"dot-green-fq"},
{"NEIGHBORHOOD":"South Lakeview","COLOR":"dot-orange-lt"},
{"NEIGHBORHOOD":"lakeview south","COLOR":"dot-orange-lt"},
{"NEIGHBORHOOD":"Lakewood North","COLOR":"dot-brown-lt"},
{"NEIGHBORHOOD":"Lakewood South","COLOR":"dot-brown-lt"},
{"NEIGHBORHOOD":"Lakewood","COLOR":"dot-brown-lt"},
{"NEIGHBORHOOD":"Lakefront","COLOR":"dot-pink"},
{"NEIGHBORHOOD":"Da Lakefront","COLOR":"dot-pink"},
{"NEIGHBORHOOD":"Lake Front","COLOR":"dot-pink"},
{"NEIGHBORHOOD":"Lake shore West","COLOR":"dot-green"},
{"NEIGHBORHOOD":"Lakeshore West","COLOR":"dot-green"},
{"NEIGHBORHOOD":"Lake shore East","COLOR":"dot-green"},
{"NEIGHBORHOOD":"Lakeshore East","COLOR":"dot-green"},
{"NEIGHBORHOOD":"Lakeshore","COLOR":"dot-green"},
{"NEIGHBORHOOD":"Lake shore","COLOR":"dot-green"},
{"NEIGHBORHOOD":"Lake Vista","COLOR":"dot-yellow"},
{"NEIGHBORHOOD":"Lakevista","COLOR":"dot-yellow"},
{"NEIGHBORHOOD":"Lake Vista, NOT Lakeview which is S of RE Lee","COLOR":"dot-yellow"},
{"NEIGHBORHOOD":"Lake Terrace","COLOR":"dot-blue-navy"},
{"NEIGHBORHOOD":"Lake Oaks","COLOR":"dot-aqua"},
{"NEIGHBORHOOD":"Gentilly","COLOR":"dot-purple"},
{"NEIGHBORHOOD":"Gentily","COLOR":"dot-purple"},
{"NEIGHBORHOOD":"Gentle Gentilly","COLOR":"dot-purple"},
{"NEIGHBORHOOD":"Chilly Gentilly","COLOR":"dot-purple"},
{"NEIGHBORHOOD":"Gentally","COLOR":"dot-purple"},
{"NEIGHBORHOOD":"The 'Tilly","COLOR":"dot-purple"},
{"NEIGHBORHOOD":"Gentilly Brah","COLOR":"dot-purple"},
{"NEIGHBORHOOD":"Bancroft Parc","COLOR":"dot-scarlet"},
{"NEIGHBORHOOD":"Bancroft Park","COLOR":"dot-scarlet"},
{"NEIGHBORHOOD":"Bancroft","COLOR":"dot-scarlet"},
{"NEIGHBORHOOD":"Oak Park","COLOR":"dot-green-dull"},
{"NEIGHBORHOOD":"Oak Park, Gentilly","COLOR":"dot-green-dull"},
{"NEIGHBORHOOD":"Vista Park","COLOR":"dot-yellow-lt"},
{"NEIGHBORHOOD":"visa park","COLOR":"dot-yellow-lt"},
{"NEIGHBORHOOD":"Gentilly/Vista Park","COLOR":"dot-yellow-lt"},
{"NEIGHBORHOOD":"Vista Park in Lake Park in Gentilly","COLOR":"dot-yellow-lt"},
{"NEIGHBORHOOD":"St. Anthony","COLOR":"dot-aqua-lt"},
{"NEIGHBORHOOD":"Filmore Gardens","COLOR":"dot-orange-lt"},
{"NEIGHBORHOOD":"Fillmore Gardens","COLOR":"dot-orange-lt"},
{"NEIGHBORHOOD":"Milneburg","COLOR":"dot-brown-lt"},
{"NEIGHBORHOOD":"Milnburg","COLOR":"dot-brown-lt"},
{"NEIGHBORHOOD":"Milneberg","COLOR":"dot-brown-lt"},
{"NEIGHBORHOOD":"Seabrook","COLOR":"dot-blue-lt"},
{"NEIGHBORHOOD":"GENTILLY-SEABROOK","COLOR":"dot-blue-lt"},
{"NEIGHBORHOOD":"Pontchartrain Park","COLOR":"dot-green"},
{"NEIGHBORHOOD":"The Park","COLOR":"dot-green"},
{"NEIGHBORHOOD":"Da Park","COLOR":"dot-green"},
{"NEIGHBORHOOD":"The Park aka Pontchartrain Park","COLOR":"dot-green"},
{"NEIGHBORHOOD":"Pontilly","COLOR":"dot-gold"},
{"NEIGHBORHOOD":"Gentilly Woods","COLOR":"dot-maroon"},
{"NEIGHBORHOOD":"Gentilly Woods aka The Woods","COLOR":"dot-maroon"},
{"NEIGHBORHOOD":"Gentilly Terrace","COLOR":"dot-magenta"},
{"NEIGHBORHOOD":"gentilly retrace","COLOR":"dot-magenta"},
{"NEIGHBORHOOD":"Gentilly Heights","COLOR":"dot-purple-lt"},
{"NEIGHBORHOOD":"Voscoville","COLOR":"dot-gray-warm-lt"},
{"NEIGHBORHOOD":"Dillard","COLOR":"dot-blue"},
{"NEIGHBORHOOD":"Edgewood","COLOR":"dot-red"},
{"NEIGHBORHOOD":"Sugar Hill","COLOR":"dot-pink"},
{"NEIGHBORHOOD":"Sugar Hill, Gentilly","COLOR":"dot-pink"},
{"NEIGHBORHOOD":"Filmore","COLOR":"dot-orange"},
{"NEIGHBORHOOD":"Fillmore","COLOR":"dot-orange"},
{"NEIGHBORHOOD":"Filmoor","COLOR":"dot-orange"},
{"NEIGHBORHOOD":"Mirabeau Gardens","COLOR":"dot-green-dk"},
{"NEIGHBORHOOD":"Virgil Park","COLOR":"dot-blue-navy"},
{"NEIGHBORHOOD":"St. Roch Bend","COLOR":"dot-gray-warm"},
{"NEIGHBORHOOD":"Lower Gentilly","COLOR":"dot-rose"},
{"NEIGHBORHOOD":"Gentilly Terrace and Gardens","COLOR":"dot-scarlet"},
{"NEIGHBORHOOD":"Burbank Gardens","COLOR":"dot-green-fq"},
{"NEIGHBORHOOD":"Paris Oaks","COLOR":"dot-green-lt"},
{"NEIGHBORHOOD":"Bayou Vista","COLOR":"dot-green-lt"},
{"NEIGHBORHOOD":"St. Bernard","COLOR":"dot-brown-dk"},
{"NEIGHBORHOOD":"Pilotland","COLOR":"dot-yellow"},
{"NEIGHBORHOOD":"Pilotland /Gentilly","COLOR":"dot-yellow"},
{"NEIGHBORHOOD":"St. Bernard Projects","COLOR":"dot-gray-cool-dk"},
{"NEIGHBORHOOD":"Columbia Parc","COLOR":"dot-gray-cool-dk"},
{"NEIGHBORHOOD":"DeSaix","COLOR":"dot-tan"},
{"NEIGHBORHOOD":"6th Ward","COLOR":"dot-purple-lt"},
{"NEIGHBORHOOD":"7th Ward","COLOR":"dot-aqua"},
{"NEIGHBORHOOD":"Seventh Ward","COLOR":"dot-aqua"},
{"NEIGHBORHOOD":"The 7","COLOR":"dot-aqua"},
{"NEIGHBORHOOD":"7th","COLOR":"dot-aqua"},
{"NEIGHBORHOOD":"Seventh","COLOR":"dot-aqua"},
{"NEIGHBORHOOD":"Middle of the 7 ward","COLOR":"dot-aqua"},
{"NEIGHBORHOOD":"Fairgrounds Triangle","COLOR":"dot-gray-cool-lt"},
{"NEIGHBORHOOD":"South 7th Ward","COLOR":"dot-aqua-lt"},
{"NEIGHBORHOOD":"Lower 7th Ward","COLOR":"dot-aqua-lt"},
{"NEIGHBORHOOD":"South Seventh Ward","COLOR":"dot-aqua-lt"},
{"NEIGHBORHOOD":"Lower 7th Ward","COLOR":"dot-aqua-lt"},
{"NEIGHBORHOOD":"Lower Seventh Ward","COLOR":"dot-aqua-lt"},
{"NEIGHBORHOOD":"S. 7th Ward","COLOR":"dot-aqua-lt"},
{"NEIGHBORHOOD":"S. Seventh Ward","COLOR":"dot-aqua-lt"},
{"NEIGHBORHOOD":"Upper 9th Ward","COLOR":"dot-yellow"},
{"NEIGHBORHOOD":"The Upper 9/ The New Houses","COLOR":"dot-yellow"},
{"NEIGHBORHOOD":"Upper Nine","COLOR":"dot-yellow"},
{"NEIGHBORHOOD":"Upper 9","COLOR":"dot-yellow"},
{"NEIGHBORHOOD":"Upper 9th","COLOR":"dot-yellow"},
{"NEIGHBORHOOD":"Upper Ninth Ward","COLOR":"dot-yellow"},
{"NEIGHBORHOOD":"9th Ward","COLOR":"dot-yellow-lt"},
{"NEIGHBORHOOD":"straight up 9th ward","COLOR":"dot-yellow-lt"},
{"NEIGHBORHOOD":"Ninth Ward","COLOR":"dot-yellow-lt"},
{"NEIGHBORHOOD":"Nint Wawrd","COLOR":"dot-yellow-lt"},
{"NEIGHBORHOOD":"Night' Ward","COLOR":"dot-yellow-lt"},
{"NEIGHBORHOOD":"THE 9 BABY","COLOR":"dot-yellow-lt"},
{"NEIGHBORHOOD":"Desire","COLOR":"dot-green-lt"},
{"NEIGHBORHOOD":"Liberty Terrace","COLOR":"dot-blue-navy"},
{"NEIGHBORHOOD":"Desire Development","COLOR":"dot-green-dk"},
{"NEIGHBORHOOD":"Desire Projects","COLOR":"dot-green-dk"},
{"NEIGHBORHOOD":"The Estates","COLOR":"dot-green-dk"},
{"NEIGHBORHOOD":"Abundance Square","COLOR":"dot-green-dk"},
{"NEIGHBORHOOD":"Florida","COLOR":"dot-orange-lt"},
{"NEIGHBORHOOD":"Florida Development","COLOR":"dot-orange"},
{"NEIGHBORHOOD":"Florida Projects","COLOR":"dot-orange"},
{"NEIGHBORHOOD":"St. Claude","COLOR":"dot-blue-lt"},
{"NEIGHBORHOOD":"Bunny Friend, or The Upper Ninth","COLOR":"dot-pink"},
{"NEIGHBORHOOD":"Bunny Friend","COLOR":"dot-pink"},
{"NEIGHBORHOOD":"Bywater","COLOR":"dot-blue-mud"},
{"NEIGHBORHOOD":"Bywata","COLOR":"dot-blue-mud"},
{"NEIGHBORHOOD":"Byway we","COLOR":"dot-blue-mud"},
{"NEIGHBORHOOD":"da bywater","COLOR":"dot-blue-mud"},
{"NEIGHBORHOOD":"Bywater; Downtown","COLOR":"dot-blue-mud"},
{"NEIGHBORHOOD":"The Barmuda Triangle of the Bywater","COLOR":"dot-blue-mud"},
{"NEIGHBORHOOD":"Upper 9th Ward/Bywater","COLOR":"dot-blue-mud"},
{"NEIGHBORHOOD":"Lower 9th Ward","COLOR":"dot-gray-cool-lt"},
{"NEIGHBORHOOD":"Lower 9th","COLOR":"dot-gray-cool-lt"},
{"NEIGHBORHOOD":"Lower Ninth Ward","COLOR":"dot-gray-cool-lt"},
{"NEIGHBORHOOD":"The Lower Nine","COLOR":"dot-gray-cool-lt"},
{"NEIGHBORHOOD":"lower 9","COLOR":"dot-gray-cool-lt"},
{"NEIGHBORHOOD":"L9W","COLOR":"dot-gray-cool-lt"},
{"NEIGHBORHOOD":"Da lowah 9th","COLOR":"dot-gray-cool-lt"},
{"NEIGHBORHOOD":"Lower Ninth","COLOR":"dot-gray-cool-lt"},
{"NEIGHBORHOOD":"Holy Cross","COLOR":"dot-maroon"},
{"NEIGHBORHOOD":"Treme","COLOR":"dot-brown-lt"},
{"NEIGHBORHOOD":"The Treme","COLOR":"dot-brown-lt"},
{"NEIGHBORHOOD":"tremé","COLOR":"dot-brown-lt"},
{"NEIGHBORHOOD":"The Treme","COLOR":"dot-brown-lt"},
{"NEIGHBORHOOD":"Faubourg Treme","COLOR":"dot-brown-lt"},
{"NEIGHBORHOOD":"kTreme","COLOR":"dot-brown-lt"},
{"NEIGHBORHOOD":"Treme Iberville","COLOR":"dot-brown-lt"},
{"NEIGHBORHOOD":"Iberville Treme","COLOR":"dot-brown-lt"},
{"NEIGHBORHOOD":"Iberville-Treme","COLOR":"dot-brown-lt"},
{"NEIGHBORHOOD":"Historic Treme","COLOR":"dot-brown-lt"},
{"NEIGHBORHOOD":"Treme-Lafitte","COLOR":"dot-brown-lt"},
{"NEIGHBORHOOD":"Mid-City","COLOR":"dot-red"},
{"NEIGHBORHOOD":"Midcity","COLOR":"dot-red"},
{"NEIGHBORHOOD":"Mid City","COLOR":"dot-red"},
{"NEIGHBORHOOD":"da mid city","COLOR":"dot-red"},
{"NEIGHBORHOOD":"Mid-City/Park aka Endymionville","COLOR":"dot-red"},
{"NEIGHBORHOOD":"the fringe of mid-city","COLOR":"dot-red"},
{"NEIGHBORHOOD":"Mid City Triangle","COLOR":"dot-red"},
{"NEIGHBORHOOD":"Lower MidCity","COLOR":"dot-red"},
{"NEIGHBORHOOD":"Lower Mid City","COLOR":"dot-red"},
{"NEIGHBORHOOD":"Lower Mid-City","COLOR":"dot-red"},
{"NEIGHBORHOOD":"Mid City!","COLOR":"dot-red"},
{"NEIGHBORHOOD":"mid pretty","COLOR":"dot-red"},
{"NEIGHBORHOOD":"Banks","COLOR":"dot-yellow-lt"},
{"NEIGHBORHOOD":"Tulane-Gravier","COLOR":"dot-green-lt"},
{"NEIGHBORHOOD":"Tulane","COLOR":"dot-green-lt"},
{"NEIGHBORHOOD":"Gravier","COLOR":"dot-green-lt"},
{"NEIGHBORHOOD":"New City","COLOR":"dot-gray-cool-med"},
{"NEIGHBORHOOD":"Fair Grounds","COLOR":"dot-green-dk"},
{"NEIGHBORHOOD":"Fairground","COLOR":"dot-green-dk"},
{"NEIGHBORHOOD":"Fairgrounds","COLOR":"dot-green-dk"},
{"NEIGHBORHOOD":"Jazzfest parking ","COLOR":"dot-green-dk"},
{"NEIGHBORHOOD":"The Ridge / 7 ward","COLOR":"dot-orange-lt"},
{"NEIGHBORHOOD":"The Ridge","COLOR":"dot-orange-lt"},
{"NEIGHBORHOOD":"Esplanade Ridge","COLOR":"dot-orange-lt"},
{"NEIGHBORHOOD":"Esplanade","COLOR":"dot-orange-lt"},
{"NEIGHBORHOOD":"St John fabroug","COLOR":"dot-blue-royal"},
{"NEIGHBORHOOD":"Faubourg St. John","COLOR":"dot-blue-royal"},
{"NEIGHBORHOOD":"Bayou St John","COLOR":"dot-blue-royal"},
{"NEIGHBORHOOD":"Bayou St. John","COLOR":"dot-blue-royal"},
{"NEIGHBORHOOD":"Bayou Saint John","COLOR":"dot-blue-royal"},
{"NEIGHBORHOOD":"The Bayou","COLOR":"dot-blue-royal"},
{"NEIGHBORHOOD":"St. John","COLOR":"dot-blue-royal"},
{"NEIGHBORHOOD":"Iberville","COLOR":"dot-green-dull"},
{"NEIGHBORHOOD":"Iberville Projects","COLOR":"dot-green-dull"},
{"NEIGHBORHOOD":"Lafitte Projects","COLOR":"dot-yellow"},
{"NEIGHBORHOOD":"Lafitte","COLOR":"dot-yellow"},
{"NEIGHBORHOOD":"Golden Triangle","COLOR":"dot-gold"},
{"NEIGHBORHOOD":"City Park Triangle","COLOR":"dot-gold"},
{"NEIGHBORHOOD":"Parkview","COLOR":"dot-green"},
{"NEIGHBORHOOD":"Park View","COLOR":"dot-green"},
{"NEIGHBORHOOD":"midcity parkview","COLOR":"dot-green"},
{"NEIGHBORHOOD":"Parkview / Bayou St. John","COLOR":"dot-green"},
{"NEIGHBORHOOD":"Gert Town","COLOR":"dot-yellow"},
{"NEIGHBORHOOD":"Gerttown","COLOR":"dot-yellow"},
{"NEIGHBORHOOD":"Gertown","COLOR":"dot-yellow"},
{"NEIGHBORHOOD":"Zion City","COLOR":"dot-maroon"},
{"NEIGHBORHOOD":"Zion","COLOR":"dot-maroon"},
{"NEIGHBORHOOD":"Hollygrove","COLOR":"dot-purple"},
{"NEIGHBORHOOD":"Holly Grove","COLOR":"dot-purple"},
{"NEIGHBORHOOD":"Palm Air","COLOR":"dot-green-dk"},
{"NEIGHBORHOOD":"Palm-Air","COLOR":"dot-green-dk"},
{"NEIGHBORHOOD":"Dixon","COLOR":"dot-aqua"},
{"NEIGHBORHOOD":"CBD","COLOR":"dot-magenta"},
{"NEIGHBORHOOD":"The CBD","COLOR":"dot-magenta"},
{"NEIGHBORHOOD":"Central Business Dist","COLOR":"dot-magenta"},
{"NEIGHBORHOOD":"Central Business District","COLOR":"dot-magenta"},
{"NEIGHBORHOOD":"Thu See Bee Dee","COLOR":"dot-magenta"},
{"NEIGHBORHOOD":"Downtown New Orleans","COLOR":"dot-black"},
{"NEIGHBORHOOD":"Downtown N.O.","COLOR":"dot-black"},
{"NEIGHBORHOOD":"Downtown NOLA","COLOR":"dot-black"},
{"NEIGHBORHOOD":"Downtown","COLOR":"dot-black"},
{"NEIGHBORHOOD":"Warehouse District","COLOR":"dot-tan"},
{"NEIGHBORHOOD":"Warehouse Dist","COLOR":"dot-tan"},
{"NEIGHBORHOOD":"warehouse za district","COLOR":"dot-tan"},
{"NEIGHBORHOOD":"WHD","COLOR":"dot-tan"},
{"NEIGHBORHOOD":"Warehouse Arts District","COLOR":"dot-tan"},
{"NEIGHBORHOOD":"Lafayette Square","COLOR":"dot-green-dull"},
{"NEIGHBORHOOD":"Lafayette Square District","COLOR":"dot-green-dull"},
{"NEIGHBORHOOD":"Central City","COLOR":"dot-aqua-lt"},
{"NEIGHBORHOOD":"Cent City","COLOR":"dot-aqua-lt"},
{"NEIGHBORHOOD":"Brown's Dairy/O.C.Haley because Central City is far up..","COLOR":"dot-aqua-lt"},
{"NEIGHBORHOOD":"Hoffman Triangle","COLOR":"dot-brown-lt"},
{"NEIGHBORHOOD":"BW Cooper","COLOR":"dot-yellow-lt"},
{"NEIGHBORHOOD":"B.W. Cooper","COLOR":"dot-yellow-lt"},
{"NEIGHBORHOOD":"Cooper","COLOR":"dot-yellow-lt"},
{"NEIGHBORHOOD":"Calliope Projects","COLOR":"dot-yellow-lt"},
{"NEIGHBORHOOD":"Calliope","COLOR":"dot-yellow-lt"},
{"NEIGHBORHOOD":"Marrero Commons","COLOR":"dot-yellow-lt"},
{"NEIGHBORHOOD":"Faubourg Lafayette","COLOR":"dot-orange"},
{"NEIGHBORHOOD":"Lafayette","COLOR":"dot-orange"},
{"NEIGHBORHOOD":"Faubourg Livaudais","COLOR":"dot-purple"},
{"NEIGHBORHOOD":"Livaudais","COLOR":"dot-purple"},
{"NEIGHBORHOOD":"Melpomene Projects","COLOR":"dot-rose"},
{"NEIGHBORHOOD":"Melpomene","COLOR":"dot-rose"},
{"NEIGHBORHOOD":"Guste Apartments","COLOR":"dot-rose"},
{"NEIGHBORHOOD":"Guste Homes","COLOR":"dot-rose"},
{"NEIGHBORHOOD":"Guste","COLOR":"dot-rose"},
{"NEIGHBORHOOD":"Magnolia Projects","COLOR":"dot-red"},
{"NEIGHBORHOOD":"Magnolia","COLOR":"dot-red"},
{"NEIGHBORHOOD":"C.J. Peete","COLOR":"dot-red"},
{"NEIGHBORHOOD":"CJ Peete","COLOR":"dot-red"},
{"NEIGHBORHOOD":"CJ Peet","COLOR":"dot-red"},
{"NEIGHBORHOOD":"Harmony Oaks","COLOR":"dot-red"},
{"NEIGHBORHOOD":"Lower Garden District","COLOR":"dot-pink"},
{"NEIGHBORHOOD":"Lower Lower Garden District","COLOR":"dot-pink"},
{"NEIGHBORHOOD":"Lower Garden Dist","COLOR":"dot-pink"},
{"NEIGHBORHOOD":"LGD","COLOR":"dot-pink"},
{"NEIGHBORHOOD":"The LGD","COLOR":"dot-pink"},
{"NEIGHBORHOOD":"Lo-Guard","COLOR":"dot-pink"},
{"NEIGHBORHOOD":"upper, lower garden district","COLOR":"dot-pink"},
{"NEIGHBORHOOD":"Lower Garden","COLOR":"dot-pink"},
{"NEIGHBORHOOD":"Lowest Garden District","COLOR":"dot-pink"},
{"NEIGHBORHOOD":"St. Thomas","COLOR":"dot-gray-warm"},
{"NEIGHBORHOOD":"St. Thomas Project","COLOR":"dot-gray-warm"},
{"NEIGHBORHOOD":"St. Thomas Projects","COLOR":"dot-gray-warm"},
{"NEIGHBORHOOD":"The Thomas","COLOR":"dot-gray-warm"},
{"NEIGHBORHOOD":"RiverGarden","COLOR":"dot-gray-warm"},
{"NEIGHBORHOOD":"RiverGardens","COLOR":"dot-gray-warm"},
{"NEIGHBORHOOD":"River Gardens","COLOR":"dot-gray-warm"},
{"NEIGHBORHOOD":"River Garden","COLOR":"dot-gray-warm"},
{"NEIGHBORHOOD":"Garden District","COLOR":"dot-yellow"},
{"NEIGHBORHOOD":"Historical Garden District","COLOR":"dot-yellow"},
{"NEIGHBORHOOD":"Wrong side of tracks in Garden District","COLOR":"dot-yellow"},
{"NEIGHBORHOOD":"Gawdin Districk","COLOR":"dot-yellow"},
{"NEIGHBORHOOD":"garden district/uptown ","COLOR":"dot-yellow"},
{"NEIGHBORHOOD":"Garden Dist","COLOR":"dot-yellow"},
{"NEIGHBORHOOD":"Upper Garden District","COLOR":"dot-yellow"},
{"NEIGHBORHOOD":"Upper Garden Dist","COLOR":"dot-yellow"},
{"NEIGHBORHOOD":"Upper Garden","COLOR":"dot-yellow"},
{"NEIGHBORHOOD":"Irish Channel","COLOR":"dot-green"},
{"NEIGHBORHOOD":"Irish Chanel","COLOR":"dot-green"},
{"NEIGHBORHOOD":"da channel","COLOR":"dot-green"},
{"NEIGHBORHOOD":"Lower Irish Channel","COLOR":"dot-green"},
{"NEIGHBORHOOD":"the channel","COLOR":"dot-green"},
{"NEIGHBORHOOD":"Uptown","COLOR":"dot-orange-lt"},
{"NEIGHBORHOOD":"Upt","COLOR":"dot-orange-lt"},
{"NEIGHBORHOOD":"Up Town","COLOR":"dot-orange-lt"},
{"NEIGHBORHOOD":"uptown by the river","COLOR":"dot-orange-lt"},
{"NEIGHBORHOOD":"Uptown Construction Zone","COLOR":"dot-orange-lt"},
{"NEIGHBORHOOD":"Uptown, around the corner from the school that used to be Fortier","COLOR":"dot-orange-lt"},
{"NEIGHBORHOOD":"uptown baby!","COLOR":"dot-orange-lt"},
{"NEIGHBORHOOD":"Uptown, near Fontainebleau Drive","COLOR":"dot-orange-lt"},
{"NEIGHBORHOOD":"Way uptown","COLOR":"dot-orange-lt"},
{"NEIGHBORHOOD":"Uptown by Tipitina's","COLOR":"dot-orange-lt"},
{"NEIGHBORHOOD":"Milan","COLOR":"dot-tan"},
{"NEIGHBORHOOD":"Freret","COLOR":"dot-rose"},
{"NEIGHBORHOOD":"Ferret","COLOR":"dot-rose"},
{"NEIGHBORHOOD":"Freret Hood (The New Magazine Street)  ","COLOR":"dot-rose"},
{"NEIGHBORHOOD":"Freret St Neighborhood","COLOR":"dot-rose"},
{"NEIGHBORHOOD":"Freret Uptown","COLOR":"dot-rose"},
{"NEIGHBORHOOD":"the new freret","COLOR":"dot-rose"},
{"NEIGHBORHOOD":"New Freret","COLOR":"dot-rose"},
{"NEIGHBORHOOD":"feret","COLOR":"dot-rose"},
{"NEIGHBORHOOD":"Freret Corridor","COLOR":"dot-rose"},
{"NEIGHBORHOOD":"Uptown/Freret","COLOR":"dot-rose"},
{"NEIGHBORHOOD":"Climana","COLOR":"dot-gray-warm-dk"},
{"NEIGHBORHOOD":"Touro","COLOR":"dot-brown-dk"},
{"NEIGHBORHOOD":"Touro Bouligny","COLOR":"dot-brown-dk"},
{"NEIGHBORHOOD":"Faubourg Delachaise","COLOR":"dot-blue-royal"},
{"NEIGHBORHOOD":"Delachaise","COLOR":"dot-blue-royal"},
{"NEIGHBORHOOD":"Delachasse","COLOR":"dot-blue-royal"},
{"NEIGHBORHOOD":"Delachase","COLOR":"dot-blue-royal"},
{"NEIGHBORHOOD":"Faubourg Marengo","COLOR":"dot-yellow-lt"},
{"NEIGHBORHOOD":"Marengo","COLOR":"dot-yellow-lt"},
{"NEIGHBORHOOD":"East Riverside","COLOR":"dot-blue-lt"},
{"NEIGHBORHOOD":"West Riverside","COLOR":"dot-pink-dk"},
{"NEIGHBORHOOD":"Faubourg Avart","COLOR":"dot-black"},
{"NEIGHBORHOOD":"Avart","COLOR":"dot-black"},
{"NEIGHBORHOOD":"Burtheville","COLOR":"dot-gray-cool-lt"},
{"NEIGHBORHOOD":"Burthville","COLOR":"dot-gray-cool-lt"},
{"NEIGHBORHOOD":"Berthville","COLOR":"dot-gray-cool-lt"},
{"NEIGHBORHOOD":"Upper Hurstville","COLOR":"dot-blue-royal"},
{"NEIGHBORHOOD":"Hurstville","COLOR":"dot-blue-royal"},
{"NEIGHBORHOOD":"Audubon","COLOR":"dot-green-dk"},
{"NEIGHBORHOOD":"Audubon Park","COLOR":"dot-green-dk"},
{"NEIGHBORHOOD":"Upper Audubon","COLOR":"dot-yellow-lt"},
{"NEIGHBORHOOD":"university/uptown","COLOR":"dot-green-lt"},
{"NEIGHBORHOOD":"University (Uptown)","COLOR":"dot-green-lt"},
{"NEIGHBORHOOD":"Uptown-University","COLOR":"dot-green-lt"},
{"NEIGHBORHOOD":"Uptown- University area","COLOR":"dot-green-lt"},
{"NEIGHBORHOOD":"University Area (Uptown)","COLOR":"dot-green-lt"},
{"NEIGHBORHOOD":"Uptown/University","COLOR":"dot-green-lt"},
{"NEIGHBORHOOD":"University area","COLOR":"dot-green-lt"},
{"NEIGHBORHOOD":"uptown university ","COLOR":"dot-green-lt"},
{"NEIGHBORHOOD":"University District","COLOR":"dot-green-lt"},
{"NEIGHBORHOOD":"University","COLOR":"dot-green-lt"},
{"NEIGHBORHOOD":"Uptown Triangle","COLOR":"dot-orange"},
{"NEIGHBORHOOD":"Carrollton","COLOR":"dot-blue"},
{"NEIGHBORHOOD":"Carolton","COLOR":"dot-blue"},
{"NEIGHBORHOOD":"Carollton","COLOR":"dot-blue"},
{"NEIGHBORHOOD":"Carrolton","COLOR":"dot-blue"},
{"NEIGHBORHOOD":"Off Carrollton","COLOR":"dot-blue"},
{"NEIGHBORHOOD":"Central Carrollton","COLOR":"dot-blue"},
{"NEIGHBORHOOD":"Uptown/Carrollton","COLOR":"dot-blue"},
{"NEIGHBORHOOD":"Uptown-Carrollton","COLOR":"dot-blue"},
{"NEIGHBORHOOD":"Black Pearl","COLOR":"dot-gray-cool-dk"},
{"NEIGHBORHOOD":"The Pearl","COLOR":"dot-gray-cool-dk"},
{"NEIGHBORHOOD":"black pearl or the pearl","COLOR":"dot-gray-cool-dk"},
{"NEIGHBORHOOD":"East Carrollton","COLOR":"dot-yellow"},
{"NEIGHBORHOOD":"East Carrolton","COLOR":"dot-yellow"},
{"NEIGHBORHOOD":"East Carolton","COLOR":"dot-yellow"},
{"NEIGHBORHOOD":"Northwest Carolton","COLOR":"dot-pink"},
{"NEIGHBORHOOD":"Northwest Carrolton","COLOR":"dot-pink"},
{"NEIGHBORHOOD":"Northwest Carollton","COLOR":"dot-pink"},
{"NEIGHBORHOOD":"NW Carrollton","COLOR":"dot-pink"},
{"NEIGHBORHOOD":"Northwest Carrollton","COLOR":"dot-pink"},
{"NEIGHBORHOOD":"West Carrollton","COLOR":"dot-peach"},
{"NEIGHBORHOOD":"West Carolton","COLOR":"dot-peach"},
{"NEIGHBORHOOD":"West Carrolton","COLOR":"dot-peach"},
{"NEIGHBORHOOD":"Riverbend","COLOR":"dot-red"},
{"NEIGHBORHOOD":"River Bend","COLOR":"dot-red"},
{"NEIGHBORHOOD":"Da Bend","COLOR":"dot-red"},
{"NEIGHBORHOOD":"Uptown Riverbend","COLOR":"dot-red"},
{"NEIGHBORHOOD":"Carrollton/Riverbend","COLOR":"dot-red"},
{"NEIGHBORHOOD":"Carrollton / Riverbend","COLOR":"dot-red"},
{"NEIGHBORHOOD":"Carrollton Riverbend","COLOR":"dot-red"},
{"NEIGHBORHOOD":"Uptown Riverbend","COLOR":"dot-red"},
{"NEIGHBORHOOD":"Uptown / Riverbend","COLOR":"dot-red"},
{"NEIGHBORHOOD":"Leonidas","COLOR":"dot-blue-lt"},
{"NEIGHBORHOOD":"leanidis","COLOR":"dot-blue-lt"},
{"NEIGHBORHOOD":"Palmer Park","COLOR":"dot-green"},
{"NEIGHBORHOOD":"Lower Palmer Park West","COLOR":"dot-green"},
{"NEIGHBORHOOD":"Pension Town","COLOR":"dot-gray-warm-dk"},
{"NEIGHBORHOOD":"PensionTown","COLOR":"dot-gray-warm-dk"},
{"NEIGHBORHOOD":"Pigeon Town","COLOR":"dot-gray-warm-lt"},
{"NEIGHBORHOOD":"PigeonTown","COLOR":"dot-gray-warm-lt"},
{"NEIGHBORHOOD":"pigeon city","COLOR":"dot-gray-warm-lt"},
{"NEIGHBORHOOD":"P-Town","COLOR":"dot-gray-warm"},
{"NEIGHBORHOOD":"Fontainebleau","COLOR":"dot-gray-cool-lt"},
{"NEIGHBORHOOD":"Fontainbleau","COLOR":"dot-gray-cool-lt"},
{"NEIGHBORHOOD":"Fontainebleu","COLOR":"dot-gray-cool-lt"},
{"NEIGHBORHOOD":"Fontainbleu","COLOR":"dot-gray-cool-lt"},
{"NEIGHBORHOOD":"Fontaineblue","COLOR":"dot-gray-cool-lt"},
{"NEIGHBORHOOD":"Fountainebleau","COLOR":"dot-gray-cool-lt"},
{"NEIGHBORHOOD":"Fontainblue","COLOR":"dot-gray-cool-lt"},
{"NEIGHBORHOOD":"Fountainbleu","COLOR":"dot-gray-cool-lt"},
{"NEIGHBORHOOD":"fountanbleau","COLOR":"dot-gray-cool-lt"},
{"NEIGHBORHOOD":"fountainbleau","COLOR":"dot-gray-cool-lt"},
{"NEIGHBORHOOD":"Fontain Bleu","COLOR":"dot-gray-cool-lt"},
{"NEIGHBORHOOD":"Uptown Fountainblue","COLOR":"dot-gray-cool-lt"},
{"NEIGHBORHOOD":"Fountainbleau/ Uptown","COLOR":"dot-gray-cool-lt"},
{"NEIGHBORHOOD":"Marlyille","COLOR":"dot-green-fq"},
{"NEIGHBORHOOD":"Marlyville","COLOR":"dot-green-fq"},
{"NEIGHBORHOOD":"Marleyville- Uptown","COLOR":"dot-green-fq"},
{"NEIGHBORHOOD":"Marleyville","COLOR":"dot-green-fq"},
{"NEIGHBORHOOD":"Marigny","COLOR":"dot-orange"},
{"NEIGHBORHOOD":"da marigny","COLOR":"dot-orange"},
{"NEIGHBORHOOD":"Marginy","COLOR":"dot-orange"},
{"NEIGHBORHOOD":"Marigny Proper","COLOR":"dot-orange"},
{"NEIGHBORHOOD":"Faubourg Marigny","COLOR":"dot-orange"},
{"NEIGHBORHOOD":"New Marigny","COLOR":"dot-gold"},
{"NEIGHBORHOOD":"New Marginy","COLOR":"dot-gold"},
{"NEIGHBORHOOD":"7th Ward / New  Marigny/ Nouveau Marigny","COLOR":"dot-gold"},
{"NEIGHBORHOOD":"Nouveau Marigny","COLOR":"dot-gold"},
{"NEIGHBORHOOD":"The Nouveau Marigny Predates 7th Ward","COLOR":"dot-gold"},
{"NEIGHBORHOOD":"The New Marginy","COLOR":"dot-gold"},
{"NEIGHBORHOOD":"Marigny Triangle","COLOR":"dot-scarlet"},
{"NEIGHBORHOOD":"French Quarter","COLOR":"dot-green-fq"},
{"NEIGHBORHOOD":"quarter","COLOR":"dot-green-fq"},
{"NEIGHBORHOOD":"Vieux Carre","COLOR":"dot-green-fq"},
{"NEIGHBORHOOD":"The Quarter","COLOR":"dot-green-fq"},
{"NEIGHBORHOOD":"Da Quatas","COLOR":"dot-green-fq"},
{"NEIGHBORHOOD":"Da Quarter","COLOR":"dot-green-fq"},
{"NEIGHBORHOOD":"Tha Quarters","COLOR":"dot-green-fq"},
{"NEIGHBORHOOD":"Quahatah","COLOR":"dot-green-fq"},
{"NEIGHBORHOOD":"Upper French Quarter","COLOR":"dot-green-fq"},
{"NEIGHBORHOOD":"upper quarter","COLOR":"dot-green-fq"},
{"NEIGHBORHOOD":"Lower Quarter","COLOR":"dot-green-fq"},
{"NEIGHBORHOOD":"Lower French Quarter","COLOR":"dot-green-fq"},
{"NEIGHBORHOOD":"residential quarter","COLOR":"dot-green-fq"},
{"NEIGHBORHOOD":"residential FQ","COLOR":"dot-green-fq"},
{"NEIGHBORHOOD":"Fun Quarters","COLOR":"dot-green-fq"},
{"NEIGHBORHOOD":"French Quarters","COLOR":"dot-green-fq"},
{"NEIGHBORHOOD":"FQ","COLOR":"dot-green-fq"},
{"NEIGHBORHOOD":"Broadmoor","COLOR":"dot-blue-navy"},
{"NEIGHBORHOOD":"uptown/broadmoor","COLOR":"dot-blue-navy"},
{"NEIGHBORHOOD":"Broadmoor (Green Dot, in your face, ULI!)","COLOR":"dot-blue-navy"},
{"NEIGHBORHOOD":"Broad moor","COLOR":"dot-blue-navy"},
{"NEIGHBORHOOD":"B'moor","COLOR":"dot-blue-navy"},
{"NEIGHBORHOOD":"Broadmore","COLOR":"dot-blue-navy"},
{"NEIGHBORHOOD":"St. Roch","COLOR":"dot-gray-warm-dk"},
{"NEIGHBORHOOD":"st roch","COLOR":"dot-gray-warm-dk"},
{"NEIGHBORHOOD":"saint roch","COLOR":"dot-gray-warm-dk"},
{"NEIGHBORHOOD":"Faubourg St. Roch","COLOR":"dot-gray-warm-dk"},
{"NEIGHBORHOOD":"Algiers","COLOR":"dot-yellow"},
{"NEIGHBORHOOD":"Da Pernt","COLOR":"dot-green"},
{"NEIGHBORHOOD":"Pernt","COLOR":"dot-green"},
{"NEIGHBORHOOD":"The Point","COLOR":"dot-green"},
{"NEIGHBORHOOD":"Algiers Point ","COLOR":"dot-green"},
{"NEIGHBORHOOD":"Da Point","COLOR":"dot-green"},
{"NEIGHBORHOOD":"Algiers riverpoint","COLOR":"dot-green"},
{"NEIGHBORHOOD":"Algiers River Point","COLOR":"dot-green"},
{"NEIGHBORHOOD":"end of the point","COLOR":"dot-green"},
{"NEIGHBORHOOD":"Algiers Point","COLOR":"dot-green"},
{"NEIGHBORHOOD":"My Little Slice of Bestbank Heaven, Algiers Point!","COLOR":"dot-green"},
{"NEIGHBORHOOD":"Algiers Pointe","COLOR":"dot-green"},
{"NEIGHBORHOOD":"Old Algiers","COLOR":"dot-green-lt"},
{"NEIGHBORHOOD":"McDonogh","COLOR":"dot-gray-warm-lt"},
{"NEIGHBORHOOD":"McDonough","COLOR":"dot-gray-warm-lt"},
{"NEIGHBORHOOD":"McDonoghville","COLOR":"dot-gray-warm-lt"},
{"NEIGHBORHOOD":"McDonoughville","COLOR":"dot-gray-warm-lt"},
{"NEIGHBORHOOD":"Fischer","COLOR":"dot-rose"},
{"NEIGHBORHOOD":"Fisher","COLOR":"dot-rose"},
{"NEIGHBORHOOD":"Ficher","COLOR":"dot-rose"},
{"NEIGHBORHOOD":"Fischer Projects","COLOR":"dot-rose"},
{"NEIGHBORHOOD":"Fischer Development","COLOR":"dot-rose"},
{"NEIGHBORHOOD":"Whitney","COLOR":"dot-aqua"},
{"NEIGHBORHOOD":"Whiteney","COLOR":"dot-aqua"},
{"NEIGHBORHOOD":"Whitny","COLOR":"dot-aqua"},
{"NEIGHBORHOOD":"U.S. Naval Base","COLOR":"dot-blue-navy"},
{"NEIGHBORHOOD":"United States Naval Base","COLOR":"dot-blue-navy"},
{"NEIGHBORHOOD":"Navy Base","COLOR":"dot-blue-navy"},
{"NEIGHBORHOOD":"Naval Base","COLOR":"dot-blue-navy"},
{"NEIGHBORHOOD":"US Navy Base","COLOR":"dot-blue-navy"},
{"NEIGHBORHOOD":"Federal City","COLOR":"dot-blue-royal"},
{"NEIGHBORHOOD":"Fed City","COLOR":"dot-blue-royal"},
{"NEIGHBORHOOD":"Behrman","COLOR":"dot-peach"},
{"NEIGHBORHOOD":"Berman","COLOR":"dot-peach"},
{"NEIGHBORHOOD":"Old Aurora","COLOR":"dot-blue-lt"},
{"NEIGHBORHOOD":"Aurora West","COLOR":"dot-purple"},
{"NEIGHBORHOOD":"New Aurora","COLOR":"dot-magenta"},
{"NEIGHBORHOOD":"Algiers / Aurora","COLOR":"dot-blue"},
{"NEIGHBORHOOD":"Aurora","COLOR":"dot-blue"},
{"NEIGHBORHOOD":"Walnut Bend","COLOR":"dot-brown-dk"},
{"NEIGHBORHOOD":"Woodland Heights","COLOR":"dot-brown-lt"},
{"NEIGHBORHOOD":"Tall Timbers","COLOR":"dot-green-dk"},
{"NEIGHBORHOOD":"Real Timbers","COLOR":"dot-brown"},
{"NEIGHBORHOOD":"Park Timbers","COLOR":"dot-green"},
{"NEIGHBORHOOD":"Brechtel","COLOR":"dot-gray-cool-lt"},
{"NEIGHBORHOOD":"English Turn","COLOR":"dot-pink"},
{"NEIGHBORHOOD":"Arbors at English Turn","COLOR":"dot-pink"},
{"NEIGHBORHOOD":"Lower Coast Algiers","COLOR":"dot-blue-royal"},
{"NEIGHBORHOOD":"Lower Coast of Algiers","COLOR":"dot-blue-royal"},
{"NEIGHBORHOOD":"lower algiers","COLOR":"dot-blue-royal"},
{"NEIGHBORHOOD":"Algiers Lower Coast","COLOR":"dot-blue-royal"},
{"NEIGHBORHOOD":"Stanton","COLOR":"dot-black"},
{"NEIGHBORHOOD":"McClendonville","COLOR":"dot-orange-lt"},
{"NEIGHBORHOOD":"McClendenville","COLOR":"dot-orange-lt"},
{"NEIGHBORHOOD":"Tunisburg","COLOR":"dot-orange-lt"},
{"NEIGHBORHOOD":"Tunisberg","COLOR":"dot-orange-lt"},
{"NEIGHBORHOOD":"Tunnisburg","COLOR":"dot-orange-lt"},
{"NEIGHBORHOOD":"Tunnisberg","COLOR":"dot-orange-lt"},
{"NEIGHBORHOOD":"The Cut-Off","COLOR":"dot-red"},
{"NEIGHBORHOOD":"Cutoff","COLOR":"dot-red"},
{"NEIGHBORHOOD":"Cut Off","COLOR":"dot-red"},
{"NEIGHBORHOOD":"Bocage","COLOR":"dot-scarlet"},
{"NEIGHBORHOOD":"Westbank","COLOR":"dot-gray-cool-lt"},
{"NEIGHBORHOOD":"west bank","COLOR":"dot-gray-cool-lt"},
{"NEIGHBORHOOD":"the wild wild west bank","COLOR":"dot-gray-cool-lt"},
{"NEIGHBORHOOD":"the wank","COLOR":"dot-gray-cool-lt"},
{"NEIGHBORHOOD":"wank","COLOR":"dot-gray-cool-lt"},
{"NEIGHBORHOOD":"Da W'ank (Al-Geaz)","COLOR":"dot-gray-cool-lt"},
{"NEIGHBORHOOD":"da wank","COLOR":"dot-gray-cool-lt"},
{"NEIGHBORHOOD":"Westbank Proper","COLOR":"dot-gray-cool-lt"},
{"NEIGHBORHOOD":"the west bank","COLOR":"dot-gray-cool-lt"},
{"NEIGHBORHOOD":"The westbank","COLOR":"dot-gray-cool-lt"},
{"NEIGHBORHOOD":"Westbonk","COLOR":"dot-gray-cool-lt"},
{"NEIGHBORHOOD":"West Jeff","COLOR":"dot-gray-cool-lt"},
{"NEIGHBORHOOD":"Uptown Westbank","COLOR":"dot-gray-cool-lt"},
{"NEIGHBORHOOD":"Best Bank","COLOR":"dot-gray-cool-lt"},
{"NEIGHBORHOOD":"New Orleans East","COLOR":"dot-red"},
{"NEIGHBORHOOD":"Eastern New Orleans","COLOR":"dot-red"},
{"NEIGHBORHOOD":"East New Orleans","COLOR":"dot-red"},
{"NEIGHBORHOOD":"The East","COLOR":"dot-red"},
{"NEIGHBORHOOD":"NO East","COLOR":"dot-red"},
{"NEIGHBORHOOD":"Da East","COLOR":"dot-red"},
{"NEIGHBORHOOD":"East NO","COLOR":"dot-red"},
{"NEIGHBORHOOD":"Nola East","COLOR":"dot-red"},
{"NEIGHBORHOOD":"Pines Village","COLOR":"dot-green-dull"},
{"NEIGHBORHOOD":"Pine Village","COLOR":"dot-green-dull"},
{"NEIGHBORHOOD":"Little Woods","COLOR":"dot-yellow-lt"},
{"NEIGHBORHOOD":"Lil Woods","COLOR":"dot-yellow-lt"},
{"NEIGHBORHOOD":"Littlewoods","COLOR":"dot-yellow-lt"},
{"NEIGHBORHOOD":"Lil' Woods","COLOR":"dot-yellow-lt"},
{"NEIGHBORHOOD":"Kennilworth","COLOR":"dot-pink"},
{"NEIGHBORHOOD":"Kenilworth","COLOR":"dot-pink"},
{"NEIGHBORHOOD":"Lake Willow","COLOR":"dot-blue-lt"},
{"NEIGHBORHOOD":"Lake Barrington","COLOR":"dot-blue-navy"},
{"NEIGHBORHOOD":"Briarwood","COLOR":"dot-gray-warm-dk"},
{"NEIGHBORHOOD":"Kingswood","COLOR":"dot-gold"},
{"NEIGHBORHOOD":"Lake Forest","COLOR":"dot-green-fq"},
{"NEIGHBORHOOD":"Lake Forrest","COLOR":"dot-green-fq"},
{"NEIGHBORHOOD":"Lake Forest Estates","COLOR":"dot-green-fq"},
{"NEIGHBORHOOD":"West Lake Forest","COLOR":"dot-green-dk"},
{"NEIGHBORHOOD":"West Lake Forrest","COLOR":"dot-green-dk"},
{"NEIGHBORHOOD":"Wimbledon","COLOR":"dot-gray-cool-lt"},
{"NEIGHBORHOOD":"Plum Orchard","COLOR":"dot-purple"},
{"NEIGHBORHOOD":"Plum Orchid","COLOR":"dot-purple"},
{"NEIGHBORHOOD":"Read Blvd. West","COLOR":"dot-yellow"},
{"NEIGHBORHOOD":"Read Boulevard West","COLOR":"dot-yellow"},
{"NEIGHBORHOOD":"Read West","COLOR":"dot-yellow"},
{"NEIGHBORHOOD":"West Read","COLOR":"dot-yellow"},
{"NEIGHBORHOOD":"Read Blvd. East","COLOR":"dot-orange-lt"},
{"NEIGHBORHOOD":"Read Boulevard East","COLOR":"dot-orange-lt"},
{"NEIGHBORHOOD":"Read East","COLOR":"dot-orange-lt"},
{"NEIGHBORHOOD":"East Read","COLOR":"dot-orange-lt"},
{"NEIGHBORHOOD":"Sherwood Forest","COLOR":"dot-green"},
{"NEIGHBORHOOD":"Sherwood Forrest","COLOR":"dot-green"},
{"NEIGHBORHOOD":"Eastover","COLOR":"dot-blue"},
{"NEIGHBORHOOD":"East Over","COLOR":"dot-blue"},
{"NEIGHBORHOOD":"Village de L'Est","COLOR":"dot-aqua-lt"},
{"NEIGHBORHOOD":"Village de LEst","COLOR":"dot-aqua-lt"},
{"NEIGHBORHOOD":"Village deLEst","COLOR":"dot-aqua-lt"},
{"NEIGHBORHOOD":"Village de l'est","COLOR":"dot-aqua-lt"},
{"NEIGHBORHOOD":"The Village","COLOR":"dot-aqua-lt"},
{"NEIGHBORHOOD":"Village","COLOR":"dot-aqua-lt"},
{"NEIGHBORHOOD":"Da Village","COLOR":"dot-aqua-lt"},
{"NEIGHBORHOOD":"de L’Est","COLOR":"dot-aqua-lt"},
{"NEIGHBORHOOD":"East Village","COLOR":"dot-aqua-lt"},
{"NEIGHBORHOOD":"Village of the East","COLOR":"dot-aqua-lt"},
{"NEIGHBORHOOD":"Village East","COLOR":"dot-aqua-lt"},
{"NEIGHBORHOOD":"Viavant","COLOR":"dot-gray-cool-med"},
{"NEIGHBORHOOD":"Vivant","COLOR":"dot-gray-cool-med"},
{"NEIGHBORHOOD":"Venetian Isles","COLOR":"dot-blue-royal"},
{"NEIGHBORHOOD":"Venetian Isle","COLOR":"dot-blue-royal"},
{"NEIGHBORHOOD":"Venetien Isles","COLOR":"dot-blue-royal"},
{"NEIGHBORHOOD":"Lake Catherine","COLOR":"dot-blue-lt"},
{"NEIGHBORHOOD":"Irish Bayou","COLOR":"dot-green-fq"},
{"NEIGHBORHOOD":"Greens Ditch","COLOR":"dot-green"},
{"NEIGHBORHOOD":"Green Ditch","COLOR":"dot-green"},
{"NEIGHBORHOOD":"Chef Menteur","COLOR":"dot-red"},
{"NEIGHBORHOOD":"Chef Pass","COLOR":"dot-red"},
{"NEIGHBORHOOD":"Michoud","COLOR":"dot-green-lt"}];

var nonNOcolors = [{"NEIGHBORHOOD":"Metairie","COLOR":"dot-gray-warm-lt"},
{"NEIGHBORHOOD":"Metry","COLOR":"dot-gray-warm-lt"},
{"NEIGHBORHOOD":"Metry off Vets","COLOR":"dot-gray-warm-lt"},
{"NEIGHBORHOOD":"North Metry","COLOR":"dot-gray-warm-lt"},
{"NEIGHBORHOOD":"Metry Brah","COLOR":"dot-gray-warm-lt"},
{"NEIGHBORHOOD":"West Metry","COLOR":"dot-gray-warm-lt"},
{"NEIGHBORHOOD":"Metryview","COLOR":"dot-gray-warm-lt"},
{"NEIGHBORHOOD":"Metry Heights","COLOR":"dot-gray-warm-lt"},
{"NEIGHBORHOOD":"Metry CBD","COLOR":"dot-gray-warm-lt"},
{"NEIGHBORHOOD":"deep in da hawt of Metry","COLOR":"dot-gray-warm-lt"},
{"NEIGHBORHOOD":"East Metry","COLOR":"dot-gray-warm-lt"},
{"NEIGHBORHOOD":"Metry East","COLOR":"dot-gray-warm-lt"},
{"NEIGHBORHOOD":"Old People Metairie","COLOR":"dot-gray-warm-lt"},
{"NEIGHBORHOOD":"The NOM (Not Old Metairie)","COLOR":"dot-gray-warm-lt"},
{"NEIGHBORHOOD":"Metairie lakefront","COLOR":"dot-gray-warm-lt"},
{"NEIGHBORHOOD":"The good part of Metairie","COLOR":"dot-gray-warm-lt"},
{"NEIGHBORHOOD":"Met-tree","COLOR":"dot-gray-warm-lt"},
{"NEIGHBORHOOD":"East Metairie","COLOR":"dot-gray-warm-lt"},
{"NEIGHBORHOOD":"The new Metairie","COLOR":"dot-gray-warm-lt"},
{"NEIGHBORHOOD":"New Metairie","COLOR":"dot-gray-warm-lt"},
{"NEIGHBORHOOD":"Old Metairie","COLOR":"dot-green-lt"},
{"NEIGHBORHOOD":"ol metry","COLOR":"dot-green-lt"},
{"NEIGHBORHOOD":"ol' metry","COLOR":"dot-green-lt"},
{"NEIGHBORHOOD":"old metry","COLOR":"dot-green-lt"},
{"NEIGHBORHOOD":"ole metry","COLOR":"dot-green-lt"},
{"NEIGHBORHOOD":"Old Metry-Bonnabel","COLOR":"dot-green-lt"},
{"NEIGHBORHOOD":"Old Metairie by the Lake","COLOR":"dot-green-lt"},
{"NEIGHBORHOOD":"Metairie Club Gardens","COLOR":"dot-yellow-lt"},
{"NEIGHBORHOOD":"the gardens","COLOR":"dot-yellow-lt"},
{"NEIGHBORHOOD":"MCG","COLOR":"dot-yellow-lt"},
{"NEIGHBORHOOD":"Airline Park","COLOR":"dot-yellow"},
{"NEIGHBORHOOD":"Airline","COLOR":"dot-yellow"},
{"NEIGHBORHOOD":"The A P","COLOR":"dot-yellow"},
{"NEIGHBORHOOD":"Bridgedale","COLOR":"dot-purple"},
{"NEIGHBORHOOD":"Westgate","COLOR":"dot-pink"},
{"NEIGHBORHOOD":"West Gate","COLOR":"dot-pink"},
{"NEIGHBORHOOD":"Willowdale","COLOR":"dot-green"},
{"NEIGHBORHOOD":"Bissonet","COLOR":"dot-orange-lt"},
{"NEIGHBORHOOD":"Bissonet Plaza","COLOR":"dot-orange-lt"},
{"NEIGHBORHOOD":"Hog Alley","COLOR":"dot-scarlet"},
{"NEIGHBORHOOD":"Hawg Alley","COLOR":"dot-scarlet"},
{"NEIGHBORHOOD":"Maple Ridge","COLOR":"dot-brown"},
{"NEIGHBORHOOD":"Jefferson","COLOR":"dot-gold"},
{"NEIGHBORHOOD":"Old Jefferson","COLOR":"dot-aqua"},
{"NEIGHBORHOOD":"Old Jeff","COLOR":"dot-aqua"},
{"NEIGHBORHOOD":"Rio Vista","COLOR":"dot-yellow-lt"},
{"NEIGHBORHOOD":"Harahan","COLOR":"dot-brown-dk"},
{"NEIGHBORHOOD":"H","COLOR":"dot-brown-dk"},
{"NEIGHBORHOOD":"The H","COLOR":"dot-brown-dk"},
{"NEIGHBORHOOD":"H-town","COLOR":"dot-brown-dk"},
{"NEIGHBORHOOD":"H Town","COLOR":"dot-brown-dk"},
{"NEIGHBORHOOD":"Htown","COLOR":"dot-brown-dk"},
{"NEIGHBORHOOD":"The Han","COLOR":"dot-brown-dk"},
{"NEIGHBORHOOD":"Elmwood","COLOR":"dot-blue-navy"},
{"NEIGHBORHOOD":"Little Farms","COLOR":"dot-orange"},
{"NEIGHBORHOOD":"Lil Farms","COLOR":"dot-orange"},
{"NEIGHBORHOOD":"River Ridge","COLOR":"dot-green-dk"},
{"NEIGHBORHOOD":"Da Ridge","COLOR":"dot-green-dk"},
{"NEIGHBORHOOD":"The Ridge","COLOR":"dot-green-dk"},
{"NEIGHBORHOOD":"DA RIDGE","COLOR":"dot-green-dk"},
{"NEIGHBORHOOD":"Kenner","COLOR":"dot-blue"},
{"NEIGHBORHOOD":"Kenner City","COLOR":"dot-blue"},
{"NEIGHBORHOOD":"Kennuh","COLOR":"dot-blue"},
{"NEIGHBORHOOD":"Kenna","COLOR":"dot-blue"},
{"NEIGHBORHOOD":"Kenna Brah","COLOR":"dot-blue"},
{"NEIGHBORHOOD":"Kenner Brah","COLOR":"dot-blue"},
{"NEIGHBORHOOD":"kenner brah the lake","COLOR":"dot-blue"},
{"NEIGHBORHOOD":"North Kenna Brah","COLOR":"dot-blue"},
{"NEIGHBORHOOD":"Crime Free Kenna Brah","COLOR":"dot-blue"},
{"NEIGHBORHOOD":"Uptown Kenner","COLOR":"dot-blue"},
{"NEIGHBORHOOD":"Midwest Kenner city","COLOR":"dot-blue"},
{"NEIGHBORHOOD":"North Kenner","COLOR":"dot-blue"},
{"NEIGHBORHOOD":"South Kenna Brah","COLOR":"dot-blue"},
{"NEIGHBORHOOD":"Kenna Bra","COLOR":"dot-blue"},
{"NEIGHBORHOOD":"Hanson Place","COLOR":"dot-gold"},
{"NEIGHBORHOOD":"Hanson City","COLOR":"dot-gold"},
{"NEIGHBORHOOD":"University City","COLOR":"dot-tan"},
{"NEIGHBORHOOD":"Universal City","COLOR":"dot-tan"},
{"NEIGHBORHOOD":"Uvc","COLOR":"dot-tan"},
{"NEIGHBORHOOD":"Kenner-Metairie","COLOR":"dot-red"},
{"NEIGHBORHOOD":"kennerie","COLOR":"dot-red"},
{"NEIGHBORHOOD":"Kennairie","COLOR":"dot-red"},
{"NEIGHBORHOOD":"Kennetairie","COLOR":"dot-red"},
{"NEIGHBORHOOD":"Kennarie","COLOR":"dot-red"},
{"NEIGHBORHOOD":"Lafreniere","COLOR":"dot-green-fq"},
{"NEIGHBORHOOD":"Lafreniere Park area","COLOR":"dot-green-fq"},
{"NEIGHBORHOOD":"Lafreniere Park","COLOR":"dot-green-fq"},
{"NEIGHBORHOOD":"Driftwood","COLOR":"dot-purple-lt"},
{"NEIGHBORHOOD":"Driftwood Park","COLOR":"dot-purple-lt"},
{"NEIGHBORHOOD":"Pontchartrain Gardens","COLOR":"dot-pink"},
{"NEIGHBORHOOD":"Ponchatrain Gardens","COLOR":"dot-pink"},
{"NEIGHBORHOOD":"Pontchatrain Gardens","COLOR":"dot-pink"},
{"NEIGHBORHOOD":"Green Acres","COLOR":"dot-green"},
{"NEIGHBORHOOD":"Pontchartrain Shores","COLOR":"dot-brown-lt"},
{"NEIGHBORHOOD":"Ponchatrain Shores","COLOR":"dot-brown-lt"},
{"NEIGHBORHOOD":"Pontchatrain Shores","COLOR":"dot-brown-lt"},
{"NEIGHBORHOOD":"Ponchartrain Shores","COLOR":"dot-brown-lt"},
{"NEIGHBORHOOD":"Rio Vista","COLOR":"dot-tan"},
{"NEIGHBORHOOD":"Bucktown","COLOR":"dot-orange-lt"},
{"NEIGHBORHOOD":"uptown bucktown","COLOR":"dot-orange-lt"},
{"NEIGHBORHOOD":"Downtown Bucktown","COLOR":"dot-orange-lt"},
{"NEIGHBORHOOD":"Westbank","COLOR":"dot-gray-cool-lt"},
{"NEIGHBORHOOD":"west bank","COLOR":"dot-gray-cool-lt"},
{"NEIGHBORHOOD":"the wild wild west bank","COLOR":"dot-gray-cool-lt"},
{"NEIGHBORHOOD":"the wank","COLOR":"dot-gray-cool-lt"},
{"NEIGHBORHOOD":"wank","COLOR":"dot-gray-cool-lt"},
{"NEIGHBORHOOD":"Da W'ank (Al-Geaz)","COLOR":"dot-gray-cool-lt"},
{"NEIGHBORHOOD":"da wank","COLOR":"dot-gray-cool-lt"},
{"NEIGHBORHOOD":"Westbank Proper","COLOR":"dot-gray-cool-lt"},
{"NEIGHBORHOOD":"the west bank","COLOR":"dot-gray-cool-lt"},
{"NEIGHBORHOOD":"The westbank","COLOR":"dot-gray-cool-lt"},
{"NEIGHBORHOOD":"Westbonk","COLOR":"dot-gray-cool-lt"},
{"NEIGHBORHOOD":"West Jeff","COLOR":"dot-gray-cool-lt"},
{"NEIGHBORHOOD":"Uptown Westbank","COLOR":"dot-gray-cool-lt"},
{"NEIGHBORHOOD":"Best Bank","COLOR":"dot-gray-cool-lt"},
{"NEIGHBORHOOD":"Harvey","COLOR":"dot-red"},
{"NEIGHBORHOOD":"Harvy","COLOR":"dot-red"},
{"NEIGHBORHOOD":"Old Harvey","COLOR":"dot-pink"},
{"NEIGHBORHOOD":"Historic Harvey","COLOR":"dot-pink"},
{"NEIGHBORHOOD":"Marrero","COLOR":"dot-yellow"},
{"NEIGHBORHOOD":"Marero","COLOR":"dot-yellow"},
{"NEIGHBORHOOD":"Old Marrero","COLOR":"dot-yellow-lt"},
{"NEIGHBORHOOD":"Old Marero","COLOR":"dot-yellow-lt"},
{"NEIGHBORHOOD":"Gretna","COLOR":"dot-magenta"},
{"NEIGHBORHOOD":"Poor Side of Gretna Blvd","COLOR":"dot-magenta"},
{"NEIGHBORHOOD":"Grenta","COLOR":"dot-magenta"},
{"NEIGHBORHOOD":"the g section","COLOR":"dot-magenta"},
{"NEIGHBORHOOD":"Great-nah","COLOR":"dot-magenta"},
{"NEIGHBORHOOD":"North Gretna","COLOR":"dot-magenta"},
{"NEIGHBORHOOD":"gretna. it's safe gere","COLOR":"dot-magenta"},
{"NEIGHBORHOOD":"Old Gretna","COLOR":"dot-blue"},
{"NEIGHBORHOOD":"Garden Park","COLOR":"dot-green-dk"},
{"NEIGHBORHOOD":"Garden Park Estates","COLOR":"dot-green-dk"},
{"NEIGHBORHOOD":"GP","COLOR":"dot-green-dk"},
{"NEIGHBORHOOD":"Garden Park Extension","COLOR":"dot-green-dk"},
{"NEIGHBORHOOD":"McDonoghville","COLOR":"dot-black"},
{"NEIGHBORHOOD":"McDonoughville","COLOR":"dot-black"},
{"NEIGHBORHOOD":"Old McDonogh","COLOR":"dot-black"},
{"NEIGHBORHOOD":"Terrytown","COLOR":"dot-blue-lt"},
{"NEIGHBORHOOD":"T town","COLOR":"dot-blue-lt"},
{"NEIGHBORHOOD":"T-Town","COLOR":"dot-blue-lt"},
{"NEIGHBORHOOD":"Terrytown in ","COLOR":"dot-blue-lt"},
{"NEIGHBORHOOD":"Woodmere","COLOR":"dot-brown-lt"},
{"NEIGHBORHOOD":"WoodmereHood","COLOR":"dot-brown-lt"},
{"NEIGHBORHOOD":"The Wood","COLOR":"dot-brown-lt"},
{"NEIGHBORHOOD":"Hoodmere","COLOR":"dot-brown-lt"},
{"NEIGHBORHOOD":"Oak Knoll","COLOR":"dot-orange"},
{"NEIGHBORHOOD":"Back of Ames","COLOR":"dot-purple"},
{"NEIGHBORHOOD":"Back-of-Ames","COLOR":"dot-purple"},
{"NEIGHBORHOOD":"Ames Garden (Bac-A-Ames)","COLOR":"dot-purple"},
{"NEIGHBORHOOD":"BOA","COLOR":"dot-purple"},
{"NEIGHBORHOOD":"Westwego","COLOR":"dot-tan"},
{"NEIGHBORHOOD":"wego","COLOR":"dot-tan"},
{"NEIGHBORHOOD":"west wego","COLOR":"dot-tan"},
{"NEIGHBORHOOD":"Waggaman","COLOR":"dot-brown"},
{"NEIGHBORHOOD":"Wagaman","COLOR":"dot-brown"},
{"NEIGHBORHOOD":"Waggamen","COLOR":"dot-brown"},
{"NEIGHBORHOOD":"Wag","COLOR":"dot-brown"},
{"NEIGHBORHOOD":"Destrehan","COLOR":"dot-blue-mud"},
{"NEIGHBORHOOD":"dhan","COLOR":"dot-blue-mud"},
{"NEIGHBORHOOD":"Ormond","COLOR":"dot-green-lt"},
{"NEIGHBORHOOD":"Ormond Estates","COLOR":"dot-green-lt"},
{"NEIGHBORHOOD":"New Sarpy","COLOR":"dot-orange"},
{"NEIGHBORHOOD":"Sarpy","COLOR":"dot-orange"},
{"NEIGHBORHOOD":"Hahnville","COLOR":"dot-gray-cool-dk"},
{"NEIGHBORHOOD":"Hville","COLOR":"dot-gray-cool-dk"},
{"NEIGHBORHOOD":"H-ville","COLOR":"dot-gray-cool-dk"},
{"NEIGHBORHOOD":"Mimosa","COLOR":"dot-maroon"},
{"NEIGHBORHOOD":"Mandeville","COLOR":"dot-blue-navy"},
{"NEIGHBORHOOD":"Da Ville","COLOR":"dot-blue-navy"},
{"NEIGHBORHOOD":"Mandeville - So Many People, So Proud of Nothing","COLOR":"dot-blue-navy"},
{"NEIGHBORHOOD":"The OG Mandeville","COLOR":"dot-blue-navy"},
{"NEIGHBORHOOD":"Mandevanilla","COLOR":"dot-blue-navy"},
{"NEIGHBORHOOD":"Old Mandeville","COLOR":"dot-blue-royal"},
{"NEIGHBORHOOD":"Old M-Ville","COLOR":"dot-blue-royal"},
{"NEIGHBORHOOD":"The O.M.","COLOR":"dot-blue-royal"},
{"NEIGHBORHOOD":"The OM","COLOR":"dot-blue-royal"},
{"NEIGHBORHOOD":"Northshore","COLOR":"dot-purple-lt"},
{"NEIGHBORHOOD":"North Shore","COLOR":"dot-purple-lt"},
{"NEIGHBORHOOD":"It's ALL Northshore!","COLOR":"dot-purple-lt"},
{"NEIGHBORHOOD":"Madisonville","COLOR":"dot-yellow"},
{"NEIGHBORHOOD":"Madisonville by the museum","COLOR":"dot-yellow"},
{"NEIGHBORHOOD":"The Dell","COLOR":"dot-pink"},
{"NEIGHBORHOOD":"The Dirty Dell","COLOR":"dot-pink"},
{"NEIGHBORHOOD":"Slidell","COLOR":"dot-orange"},
{"NEIGHBORHOOD":"Covington","COLOR":"dot-red"},
{"NEIGHBORHOOD":"Cov","COLOR":"dot-red"},
{"NEIGHBORHOOD":"Downtown Covington","COLOR":"dot-red"},
{"NEIGHBORHOOD":"Downtown Cov","COLOR":"dot-red"},
{"NEIGHBORHOOD":"New Covington","COLOR":"dot-red"},
{"NEIGHBORHOOD":"Old Covington","COLOR":"dot-magenta"},
{"NEIGHBORHOOD":"Tammany Hills","COLOR":"dot-green-fq"},
{"NEIGHBORHOOD":"Abita Springs","COLOR":"dot-purple"},
{"NEIGHBORHOOD":"Abita","COLOR":"dot-purple"},
{"NEIGHBORHOOD":"A-bee-DAT Springs YAT","COLOR":"dot-purple"},
{"NEIGHBORHOOD":"Arabi","COLOR":"dot-orange"},
{"NEIGHBORHOOD":"New Arabi","COLOR":"dot-orange"},
{"NEIGHBORHOOD":"Old Arabi","COLOR":"dot-orange-lt"},
{"NEIGHBORHOOD":"Historic Old Arabi","COLOR":"dot-orange-lt"},
{"NEIGHBORHOOD":"Uptown St. Bernard","COLOR":"dot-brown-lt"},
{"NEIGHBORHOOD":"Carolyn Park","COLOR":"dot-green-lt"},
{"NEIGHBORHOOD":"Chalmette","COLOR":"dot-purple"},
{"NEIGHBORHOOD":"Heart of Chalmette","COLOR":"dot-purple"},
{"NEIGHBORHOOD":"The Parish","COLOR":"dot-green-fq"},
{"NEIGHBORHOOD":"Da Parish","COLOR":"dot-green-fq"},
{"NEIGHBORHOOD":"St. Bernard Parish","COLOR":"dot-green-fq"},
{"NEIGHBORHOOD":"Meraux","COLOR":"dot-blue-royal"},
{"NEIGHBORHOOD":"Lexington","COLOR":"dot-gray-cool-dk"},
{"NEIGHBORHOOD":"Lexington Place","COLOR":"dot-gray-cool-dk"},
{"NEIGHBORHOOD":"Violet","COLOR":"dot-purple-lt"},
{"NEIGHBORHOOD":"Belle Chasse","COLOR":"dot-green-dull"}];

var dotlist = [
"dot-aqua-lt",
"dot-aqua",
"dot-blue-lt",
"dot-blue-mud",
"dot-blue-navy",
"dot-blue-royal",
"dot-blue",
"dot-brown-dk",
"dot-brown-lt",
"dot-brown",
"dot-gold",
"dot-gray-cool-dk",
"dot-gray-cool-lt",
"dot-gray-cool-med",
"dot-gray-warm-dk",
"dot-gray-warm-lt",
"dot-gray-warm",
"dot-green-dk",
"dot-green-dull",
"dot-green-fq",
"dot-green-lt",
"dot-green",
"dot-magenta",
"dot-maroon",
"dot-orange-lt",
"dot-orange",
"dot-peach",
"dot-pink-dk",
"dot-pink",
"dot-purple-lt",
"dot-purple",
"dot-red",
"dot-rose",
"dot-scarlet",
"dot-tan",
"dot-yellow-lt",
"dot-yellow"
];